### ISSUE TITLE
CRASH - G3 LCE - macOS 10.15.7

### ISSUE THREAD

**Issue by etunni** [eweracs/Italify#1]
**This is the message at macro panel**

A plugin caused a crash

The Plugin Italify.glyphsFilter has caused a crash. Please update it by opening the Plugin Manager or re-downloading it from the original source.

Details:
Traceback (most recent call last):

File "[plugin.py](http://plugin.py/)", line 87, in setDistinquishStraightAndCurved_
Glyphs.boolDefaults["com.eweracs.italify.distinquishStraightAndCurved"] = sender.state()

File "GlyphsApp/GlyphsApp/__init__.py", line 900, in __setitem__

TypeError: boolDefaults only accepts values of type bool, not int

App:3.1.1-3139 Plugin:1.0-1

**Comment by chrisjansky** [comment]
Same here 🙂

**Comment by eweracs** [comment]
Hi, apologies for fixing this so late. This is fixed in e54c0d5
